# Generated by Django 3.1.5 on 2021-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=50, verbose_name='Автор')),
                ('desc_author', models.TextField(blank=True, max_length=50, null=True, verbose_name='Краткая информация об автора')),
            ],
        ),
    ]
