# Generated by Django 3.1.5 on 2021-02-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_genre_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=80, verbose_name='Название книги')),
                ('created', models.DateTimeField(verbose_name='Название книги')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Название книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Автор1', to='references.author', verbose_name='Автор')),
            ],
        ),
    ]
