# Generated by Django 3.1.5 on 2021-02-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(to='references.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
