# Generated by Django 3.1.5 on 2021-02-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_auto_20210203_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_restrict',
            field=models.CharField(max_length=50, null=True, verbose_name='Возрастные ограничения'),
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Переплет'),
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Страниц'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес(гр)'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год издания'),
        ),
    ]
