# Generated by Django 3.1.5 on 2021-02-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20210203_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
