# Generated by Django 3.1.5 on 2021-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
    ]
