# Generated by Django 3.1.5 on 2021-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_auto_20210211_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book'),
        ),
    ]
