# Generated by Django 3.1.5 on 2021-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_auto_20210224_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='desc_genre',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Краткая информация о Жанре'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='desc_publisher',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Краткая информация об Издателе'),
        ),
        migrations.AddField(
            model_name='series',
            name='desc_series',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Краткая информация о серии'),
        ),
    ]
