# Generated by Django 3.1.5 on 2021-03-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_auto_20210226_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_format', models.CharField(max_length=80, verbose_name='Название формата')),
                ('desc_format', models.TextField(verbose_name='Описание формата')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='format',
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.ManyToManyField(to='references.Format', verbose_name='Формат'),
        ),
    ]
