# Generated by Django 3.1.5 on 2021-03-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_auto_20210311_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Формат', 'verbose_name_plural': 'Форматы'},
        ),
    ]
