# Generated by Django 3.1.5 on 2021-03-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0017_auto_20210311_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='desc_format',
        ),
    ]
