# Generated by Django 3.1.5 on 2021-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_remove_format_desc_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='desc_format',
            field=models.TextField(blank=True, null=True, verbose_name='Описание формата'),
        ),
    ]
