# Generated by Django 3.1.5 on 2021-03-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0019_format_desc_format'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Format',
            new_name='Formats',
        ),
    ]
