# Generated by Django 3.1.5 on 2021-03-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_auto_20210311_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='format',
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='references.formats', verbose_name='Формат'),
        ),
    ]
