# Generated by Django 3.1.5 on 2021-03-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_auto_20210312_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN'),
        ),
    ]
