# Generated by Django 3.1.5 on 2021-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0023_auto_20210312_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='http://placehold.it/700x400', null=True, upload_to='image/'),
        ),
    ]
