# Generated by Django 3.1.5 on 2021-03-19 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Пользватель')),
                ('phone', models.CharField(blank=True, default='', max_length=80, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default='', max_length=80, verbose_name='Город')),
                ('post_index', models.CharField(blank=True, default='', max_length=80, verbose_name='Почтовый индекс')),
                ('address1', models.CharField(blank=True, default='', max_length=120, verbose_name='Адрес 1')),
                ('address2', models.CharField(blank=True, default='', max_length=120, verbose_name='Адрес 2')),
            ],
        ),
    ]
